"""remove

Revision ID: 17b67baf2b2d
Revises: c2056b9bf69f
Create Date: 2026-04-17 16:32:06.083325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b67baf2b2d'
down_revision = 'c2056b9bf69f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
