"""add

Revision ID: c2056b9bf69f
Revises: 7fbfbc61c554
Create Date: 2026-04-17 16:07:49.573113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2056b9bf69f'
down_revision = '7fbfbc61c554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=True))

    with op.batch_alter_table('user_skill', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_skill_user_id_skill_id', ['user_id', 'skill_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_skill', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_skill_user_id_skill_id', type_='unique')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
